name: test_iis_config_extraction
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execute the tests suite
        uses: Amadevus/pwsh-script@v2.0.0
        with:
          script:  test_iis_config_extraction.ps1
